-- SQL to seed for the usergroup testing

INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES
(2,	'zwillms',	'$P$BqUbO.P2h0jzD3Fo/JPHwWvXzecFTT/',	'christina-oconnell',	'roma24@example.org',	'http://www.marquardt.com/corrupti-quo-consectetur-delectus-et-ipsa-eaque-similique-et',	'2022-10-02 13:13:33',	'',	0,	'Britney'),
(3,	'bette.friesen',	'$P$BLmulSaDmcqfrMpry1UEPa8FVJ1G8s1',	'mccullough-minnie',	'earl77@example.com',	'http://www.weber.com/dolores-minima-hic-libero-illo.html',	'2022-10-02 16:35:38',	'',	0,	'Ayden'),
(4,	'rbrekke',	'$P$BJGPwyL70w7OLwHajE8ukqLlWerJZT.',	'baufderhar',	'jaylin04@example.net',	'http://www.balistreri.com/aut-et-odit-sed-est-eius.html',	'2022-10-03 02:53:16',	'',	0,	'Garnet'),
(5,	'rahsaan.wisozk',	'$P$BTg.BJ8kRVwNR29ljb65Az74e5P6Cg0',	'mosciski-ena',	'pierce87@example.com',	'http://abshire.com/autem-ea-odio-sint',	'2022-10-03 18:37:10',	'',	0,	'Delpha'),
(6,	'vergie.stokes',	'$P$BjXuQXKuBbM4JNiMbusKqDdRbKdcF6/',	'vfriesen',	'huel.holden@example.org',	'http://www.halvorson.net/voluptatem-doloribus-non-cum-rem-illum-nam-beatae',	'2022-10-03 12:00:57',	'',	0,	'Beverly'),
(7,	'wilbert00',	'$P$BlVgOhbCuZU7RUA0RaoIqGPExXLcCb.',	'qjacobi',	'sipes.gino@example.net',	'http://www.quitzon.com/quidem-quidem-officiis-aliquid-quo-laborum.html',	'2022-10-02 23:25:27',	'',	0,	'Norwood'),
(8,	'gleason.jeff',	'$P$BoRpFfulOlI/9uMRMcxvXzoWlcCPIk.',	'kgreen',	'rschaefer@example.com',	'http://www.leffler.com/a-aut-dolores-accusamus-est',	'2022-10-03 01:43:26',	'',	0,	'Bernie'),
(9,	'orpha.von',	'$P$B2Z/U1thVqjFwr4u.4vnb8yo2pYfWx0',	'jast-tony',	'ryan.vida@example.com',	'https://www.haag.net/repudiandae-sed-totam-dolore',	'2022-10-02 03:54:31',	'',	0,	'Ettie'),
(10,	'gutmann.amara',	'$P$B8H7.uUe4BhFNtABmFHgiks/PcKD8W1',	'amely01',	'nienow.frank@example.net',	'http://www.volkman.net/non-magnam-rem-doloremque-qui-consectetur-necessitatibus-voluptas-rerum',	'2022-10-03 03:57:42',	'',	0,	'Jayden'),
(11,	'stehr.loraine',	'$P$BGn3XiVhHBlnllWgWKTlf/TI3UIM4Y1',	'darrin34',	'rrutherford@example.org',	'http://rosenbaum.info/iste-autem-quia-aut-eum-quia',	'2022-10-03 19:53:58',	'',	0,	'Roslyn');

INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES
(24,	2,	'nickname',	'imayer'),
(25,	2,	'first_name',	'Kamren'),
(26,	2,	'last_name',	'Renner'),
(27,	2,	'description',	'Sit ut nemo exercitationem vitae qui. Facilis omnis aspernatur molestiae. Ipsa molestias et quo. Odit reprehenderit repellendus laboriosam veritatis voluptas.\r\n\r\nDucimus eligendi ipsum qui nobis sit molestiae magni neque. Amet repellat quis iste qui. Debitis sunt consequatur reiciendis sint itaque dolor.'),
(28,	2,	'rich_editing',	'true'),
(29,	2,	'syntax_highlighting',	'true'),
(30,	2,	'comment_shortcuts',	'false'),
(31,	2,	'admin_color',	'fresh'),
(32,	2,	'use_ssl',	'0'),
(33,	2,	'show_admin_bar_front',	'true'),
(34,	2,	'locale',	''),
(35,	2,	'wp_capabilities',	'a:1:{s:6:\"editor\";b:1;}'),
(36,	2,	'wp_user_level',	'7'),
(37,	2,	'dismissed_wp_pointers',	''),
(38,	2,	'fakerpress_flag',	'1'),
(39,	2,	'sms_number',	'7988550263'),
(40,	2,	'sms_usergroup',	'users_active'),
(198,	2,	'birthday',	'1969-07-12'),
(41,	3,	'nickname',	'ruben33'),
(42,	3,	'first_name',	'Jammie'),
(43,	3,	'last_name',	'DuBuque'),
(44,	3,	'description',	'Saepe est voluptas doloribus officiis exercitationem. Alias consequatur ex eaque et odit. Occaecati ea quibusdam facere. Voluptas exercitationem similique et necessitatibus occaecati omnis omnis.\r\n\r\nLaudantium et sint et harum commodi. Dolores a soluta quia et. Quisquam alias voluptatem asperiores architecto velit eum.\r\n\r\nDolorum ut eius consequatur officia enim itaque veritatis. Qui et tempore voluptatem sit voluptate. Perferendis quia pariatur odio ratione.'),
(45,	3,	'rich_editing',	'true'),
(46,	3,	'syntax_highlighting',	'true'),
(47,	3,	'comment_shortcuts',	'false'),
(48,	3,	'admin_color',	'fresh'),
(49,	3,	'use_ssl',	'0'),
(50,	3,	'show_admin_bar_front',	'true'),
(51,	3,	'locale',	''),
(52,	3,	'wp_capabilities',	'a:1:{s:10:\"subscriber\";b:1;}'),
(53,	3,	'wp_user_level',	'0'),
(54,	3,	'dismissed_wp_pointers',	''),
(55,	3,	'fakerpress_flag',	'1'),
(56,	3,	'sms_number',	'6153149506'),
(57,	3,	'sms_usergroup',	'users_retired'),
(58,	4,	'nickname',	'william46'),
(59,	4,	'first_name',	'Janiya'),
(60,	4,	'last_name',	'Bode'),
(61,	4,	'description',	'Numquam at omnis distinctio aut enim aut quia id. Aut iste doloribus consectetur unde eos expedita impedit sint. Nulla veniam id mollitia quo voluptate voluptatem.\r\n\r\nPossimus voluptatem et ut harum earum vero doloribus. Molestiae dolore ut a. Eveniet voluptatem excepturi consequatur sint odio dolor.\r\n\r\nEt doloribus incidunt libero error. Consequatur recusandae sed eaque eligendi. Rerum quisquam corporis laboriosam non architecto. Sed ad rerum ut veritatis dolor mollitia. Veritatis laborum et eligendi expedita.'),
(62,	4,	'rich_editing',	'true'),
(63,	4,	'syntax_highlighting',	'true'),
(64,	4,	'comment_shortcuts',	'false'),
(65,	4,	'admin_color',	'fresh'),
(66,	4,	'use_ssl',	'0'),
(67,	4,	'show_admin_bar_front',	'true'),
(68,	4,	'locale',	''),
(69,	4,	'wp_capabilities',	'a:1:{s:13:\"administrator\";b:1;}'),
(70,	4,	'wp_user_level',	'10'),
(71,	4,	'dismissed_wp_pointers',	''),
(72,	4,	'fakerpress_flag',	'1'),
(73,	4,	'sms_number',	'6654420751'),
(74,	4,	'sms_usergroup',	'users_active'),
(75,	5,	'nickname',	'cody.kirlin'),
(76,	5,	'first_name',	'Ansel'),
(77,	5,	'last_name',	'Hermann'),
(78,	5,	'description',	'Voluptas voluptatem sequi numquam veritatis earum. Cum ea qui ut cum est. Modi qui et mollitia et. Voluptatem occaecati perferendis excepturi consequatur id.\r\n\r\nDolores est fuga modi delectus nesciunt eaque esse. Omnis velit harum placeat omnis. Adipisci eius eum et et qui et accusamus.\r\n\r\nPerferendis ad ut maiores quisquam sunt dicta. Consequuntur id aut magni tenetur fugit exercitationem. Expedita officia eius illo repudiandae quis est. Doloribus ea quia ea quo voluptas occaecati.'),
(79,	5,	'rich_editing',	'true'),
(80,	5,	'syntax_highlighting',	'true'),
(81,	5,	'comment_shortcuts',	'false'),
(82,	5,	'admin_color',	'fresh'),
(83,	5,	'use_ssl',	'0'),
(84,	5,	'show_admin_bar_front',	'true'),
(85,	5,	'locale',	''),
(86,	5,	'wp_capabilities',	'a:1:{s:13:\"administrator\";b:1;}'),
(87,	5,	'wp_user_level',	'10'),
(88,	5,	'dismissed_wp_pointers',	''),
(89,	5,	'fakerpress_flag',	'1'),
(90,	5,	'sms_usergroup',	'users_active'),
(91,	6,	'nickname',	'marcelina32'),
(92,	6,	'first_name',	'Verna'),
(93,	6,	'last_name',	'Lowe'),
(94,	6,	'description',	'Ipsam magnam delectus sed voluptatibus soluta quisquam. Enim in deserunt voluptates corporis nulla. Eos officia quas numquam facilis. Odit ipsam nobis sint nostrum.\r\n\r\nCumque libero officiis sunt eligendi. Non dolorum non accusamus. Ut molestiae rem maxime dolor esse quia.'),
(95,	6,	'rich_editing',	'true'),
(96,	6,	'syntax_highlighting',	'true'),
(97,	6,	'comment_shortcuts',	'false'),
(98,	6,	'admin_color',	'fresh'),
(99,	6,	'use_ssl',	'0'),
(100,	6,	'show_admin_bar_front',	'true'),
(101,	6,	'locale',	''),
(102,	6,	'wp_capabilities',	'a:1:{s:6:\"editor\";b:1;}'),
(103,	6,	'wp_user_level',	'7'),
(104,	6,	'dismissed_wp_pointers',	''),
(105,	6,	'fakerpress_flag',	'1'),
(106,	6,	'sms_number',	'3219671237'),
(107,	6,	'sms_usergroup',	'users_retired'),
(108,	7,	'nickname',	'qmonahan'),
(109,	7,	'first_name',	'Bill'),
(110,	7,	'last_name',	'Torp'),
(111,	7,	'description',	'Praesentium voluptatibus rerum distinctio voluptates praesentium. Corporis totam libero facere eos corporis non ea. At in eius sapiente ea.\r\n\r\nEt non dolore quis consequatur qui accusamus doloribus vero. Et necessitatibus quia repellendus numquam. Repellat architecto reiciendis voluptate rerum sit veniam.\r\n\r\nEt est cum est nemo. Nihil omnis corrupti et perspiciatis consectetur quam. Omnis ex quia dolor nam molestiae dicta dolores magnam. Quas illum unde magni soluta minima.'),
(112,	7,	'rich_editing',	'true'),
(113,	7,	'syntax_highlighting',	'true'),
(114,	7,	'comment_shortcuts',	'false'),
(115,	7,	'admin_color',	'fresh'),
(116,	7,	'use_ssl',	'0'),
(117,	7,	'show_admin_bar_front',	'true'),
(118,	7,	'locale',	''),
(119,	7,	'wp_capabilities',	'a:1:{s:13:\"administrator\";b:1;}'),
(120,	7,	'wp_user_level',	'10'),
(121,	7,	'dismissed_wp_pointers',	''),
(122,	7,	'fakerpress_flag',	'1'),
(123,	7,	'sms_number',	'2760785089'),
(124,	7,	'sms_usergroup',	'users_active'),
(125,	8,	'nickname',	'odessa82'),
(126,	8,	'first_name',	'Alverta'),
(127,	8,	'last_name',	'Steuber'),
(128,	8,	'description',	'Est non nobis iure. Veritatis cupiditate quo commodi. Repellat velit provident tenetur veniam. Rem atque repellendus velit.\r\n\r\nProvident debitis ut molestiae sed commodi. Optio magni minima nulla qui earum quia. Eligendi fugiat maxime incidunt amet sed. Animi occaecati similique autem libero ut sed sed.'),
(129,	8,	'rich_editing',	'true'),
(130,	8,	'syntax_highlighting',	'true'),
(131,	8,	'comment_shortcuts',	'false'),
(132,	8,	'admin_color',	'fresh'),
(133,	8,	'use_ssl',	'0'),
(134,	8,	'show_admin_bar_front',	'true'),
(135,	8,	'locale',	''),
(136,	8,	'wp_capabilities',	'a:1:{s:10:\"subscriber\";b:1;}'),
(137,	8,	'wp_user_level',	'0'),
(138,	8,	'dismissed_wp_pointers',	''),
(139,	8,	'fakerpress_flag',	'1'),
(140,	8,	'sms_number',	'5870646708'),
(141,	8,	'sms_usergroup',	'users_retired'),
(199,	8,	'birthday',	'1987-07-21'),
(142,	9,	'nickname',	'ally.koss'),
(143,	9,	'first_name',	'Elna'),
(144,	9,	'last_name',	'Medhurst'),
(145,	9,	'description',	'Soluta voluptas rerum dolores maxime. Quaerat illo aperiam consequatur expedita blanditiis. Id molestias numquam illum excepturi quo eius magni.\r\n\r\nDoloribus quasi cumque soluta commodi. Et ducimus sit sit corporis hic laboriosam earum quo.'),
(146,	9,	'rich_editing',	'true'),
(147,	9,	'syntax_highlighting',	'true'),
(148,	9,	'comment_shortcuts',	'false'),
(149,	9,	'admin_color',	'fresh'),
(150,	9,	'use_ssl',	'0'),
(151,	9,	'show_admin_bar_front',	'true'),
(152,	9,	'locale',	''),
(153,	9,	'wp_capabilities',	'a:1:{s:6:\"editor\";b:1;}'),
(154,	9,	'wp_user_level',	'7'),
(155,	9,	'dismissed_wp_pointers',	''),
(156,	9,	'fakerpress_flag',	'1'),
(157,	9,	'sms_number',	'6314113882'),
(158,	9,	'sms_usergroup',	'users_retired'),
(197,	9,	'birthday',	'1910-01-21'),
(159,	10,	'nickname',	'jessie.stroman'),
(160,	10,	'first_name',	'Constantin'),
(161,	10,	'last_name',	'Spinka'),
(162,	10,	'description',	'At magnam quibusdam modi aut eaque eum consequatur ea. Dicta qui dolorum autem officia. Quisquam facilis illo dolorem aut. Perferendis fuga id et quis ut possimus. Aut accusamus porro consequatur nemo.\r\n\r\nEt expedita perferendis eos nam architecto sit distinctio optio. Qui neque nisi dolores ut tempore. Et amet pariatur quidem temporibus laboriosam vel odio.'),
(163,	10,	'rich_editing',	'true'),
(164,	10,	'syntax_highlighting',	'true'),
(165,	10,	'comment_shortcuts',	'false'),
(166,	10,	'admin_color',	'fresh'),
(167,	10,	'use_ssl',	'0'),
(168,	10,	'show_admin_bar_front',	'true'),
(169,	10,	'locale',	''),
(170,	10,	'wp_capabilities',	'a:1:{s:10:\"subscriber\";b:1;}'),
(171,	10,	'wp_user_level',	'0'),
(172,	10,	'dismissed_wp_pointers',	''),
(173,	10,	'fakerpress_flag',	'1'),
(174,	10,	'sms_number',	'8503037034'),
(175,	10,	'sms_usergroup',	'users_active'),
(176,	11,	'nickname',	'evangeline.barton'),
(177,	11,	'first_name',	'Magdalena'),
(178,	11,	'last_name',	'Bednar'),
(179,	11,	'description',	'Illum est quam animi ducimus unde. Similique vel ipsa aut veritatis aut nesciunt recusandae. Suscipit voluptatem quis saepe omnis necessitatibus nihil et.\r\n\r\nVoluptatum autem delectus iure ea rerum in modi. Voluptatibus et hic nihil quis exercitationem quaerat voluptas. Eveniet consequuntur vel ut ratione sed laudantium sint. Enim eius minima officiis veritatis neque sit. Doloremque velit dolores consectetur qui dolor ipsam.'),
(180,	11,	'rich_editing',	'true'),
(181,	11,	'syntax_highlighting',	'true'),
(182,	11,	'comment_shortcuts',	'false'),
(183,	11,	'admin_color',	'fresh'),
(184,	11,	'use_ssl',	'0'),
(185,	11,	'show_admin_bar_front',	'true'),
(186,	11,	'locale',	''),
(187,	11,	'wp_capabilities',	'a:1:{s:13:\"administrator\";b:1;}'),
(188,	11,	'wp_user_level',	'10'),
(189,	11,	'dismissed_wp_pointers',	''),
(190,	11,	'fakerpress_flag',	'1'),
(191,	11,	'sms_number',	'6002616099'),
(192,	11,	'sms_usergroup',	'users_retired');